### ISSUE TITLE
"sails generate model" from outside of sails project directory

### ISSUE THREAD

**Issue by FurkhatKasymov** [balderdashy/sails-generate-model#10]
When I generate controller from outside of sails root project directory, I receive error:
`Sorry, this command can only be used in the root directory of a Sails project.`
When I generate model:
`info: Created a new model ("TestModel") at api/models/TestModel.js!`

I think, there should be same error message for model

My sailsjs version 0.11.2

**Comment by mikermcneil** [comment]
@FurkhatKasymov thanks!
