### ISSUE TITLE
How can I test this generator?

### ISSUE THREAD

**Issue by joelwallis** [balderdashy/sails-generate-model#8]
[I'm working on an improvement for the DX while generating models on Sails](0a3faabd64c1dce7748d768a0add81d321669125), but the README.md way to test the script does not work.

How do you test this model, and/or how can I test it to make sure my contribution is working well?

**Comment by konstantinzolotarev** [comment]
There are no tests for `sails-generate-model` exist. So only manually. Or you have to add tests =D

**Comment by joelwallis** [comment]
I'll work on something when I find some time here.
